### ISSUE TITLE
NPE in Schedulers

### ISSUE THREAD

**Issue by orkun1675** [chaseoes/TF2#39]
2013-06-08 23:19:30 [SEVERE] java.lang.NullPointerException
2013-06-08 23:19:30 [SEVERE]    at me.chaseoes.tf2.Schedulers$2.run(Schedulers.java:90)
2013-06-08 23:19:30 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:58)
2013-06-08 23:19:30 [SEVERE]    at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
2013-06-08 23:19:30 [SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:509)
2013-06-08 23:19:30 [SEVERE]    at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:227)
2013-06-08 23:19:30 [SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:472)
2013-06-08 23:19:30 [SEVERE]    at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:404)
2013-06-08 23:19:30 [SEVERE]    at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by psycowithespn** [comment]
Try the newest dev build now to see if it still happens. This error has been troubling me for a while, but I think I got it.
http://ci.chaseoes.com/job/TF2/28/

**Comment by orkun1675** [comment]
Installed on online server. Will report back.

**Comment by orkun1675** [comment]
Nope still the same error: http://pastebin.com/fdjXRimb

But I have to say that it is less frequent this time, only 4 times in a day.
