### ISSUE TITLE
Potion Effect Issue

### ISSUE THREAD

**Issue by Komod0r** [chaseoes/TF2#93]
2021-01-19 21:51:54 [SEVERE] [TF2] The error encountered while changing a player's class is above! Note that TF2 v2.0 has a new format for defining items - click here to view the new default configuration: http://goo.gl/LdKKR
2021-01-19 21:51:54 [SEVERE] java.lang.IllegalArgumentException: effect type cannot be null
2021-01-19 21:51:54 [SEVERE] 	at org.apache.commons.lang.Validate.notNull(Validate.java:203)
2021-01-19 21:51:54 [SEVERE] 	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:39)
2021-01-19 21:51:54 [SEVERE] 	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:55)
2021-01-19 21:51:54 [SEVERE] 	at me.chaseoes.tf2.classes.TF2Class.apply(TF2Class.java:64)
2021-01-19 21:51:54 [SEVERE] 	at me.chaseoes.tf2.Game$1.run(Game.java:115)
2021-01-19 21:51:54 [SEVERE] 	at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:53)
2021-01-19 21:51:54 [SEVERE] 	at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2021-01-19 21:51:54 [SEVERE] 	at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:522)
2021-01-19 21:51:54 [SEVERE] 	at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
2021-01-19 21:51:54 [SEVERE] 	at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
2021-01-19 21:51:54 [SEVERE] 	at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
2021-01-19 21:51:54 [SEVERE] 	at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)

**Comment by Komod0r** [comment]
I managed to solve issue on my own. It is caused by iConomy plugin. If you have the same problem, try to delete iConomy and try again!
